version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    volumes:
      - $(NGINX_DATA):/data
      - $(LETSENCRYPT):/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    depends_on:
      - stats
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      nginx_proxy_manager:
        ipv4_address: 172.20.0.2

  stats:
    image: justsky/goaccess-for-nginxproxymanager:latest
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      SKIP_ARCHIVED_LOGS: "${SKIP_ARCHIVED_LOGS}"
      BASIC_AUTH: "${BASIC_AUTH}"
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    ports:
      - 7880:7880
 
    volumes:
      - $(NGINX_DATA)/logs:/opt/log:ro
      - $(GOACCESS_CONFIG):/config
