version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    hostname: ${NPM_HOSTNAME}
    restart: always
    volumes:
      - ${NPM_DATA}:/data
      - ${LETSENCRYPT}:/etc/letsencrypt
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: ${DISABLE_IPV6}
      HOSTNAME: ${NPM_HOSTNAME}      
    depends_on:
      - stats
    ports:
      - 80:80
      - 443:443
      - 81:81

  stats:
    image: justsky/goaccess-for-nginxproxymanager:latest
    restart: unless-stopped
    hostname: ${GOACCESS_HOSTNAME}
    environment:
      TZ: ${TIMEZONE}
      SKIP_ARCHIVED_LOGS: "${SKIP_ARCHIVED_LOGS}"
      BASIC_AUTH: "${BASIC_AUTH}"
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      HOSTNAME: ${GOACCESS_HOSTNAME}
    ports:
      - 7880:7880
    volumes:
      - ${NPM_DATA}/logs:/opt/log:ro
      - ${GOACCESS_CONFIG}:/config
