---
services:
  portainer:
    image: portainer/${VERSION}:latest
    container_name: portainer
    restart: always
    environment:
      TZ: ${TIMEZONE}
      HOSTNAME: ${HOSTNAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9000
      - 8443:8000

volumes:
  portainer_data: