---
version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOST_FOLDER}:/app/data
    networks:
      - ${NETWORK} #If not added with portainer already
networks:
  ${NETWORK}: #If not added with portainer already
    external: true #If not added with portainer already